version: "3.7"

services:
    nginx:
        container_name: nginx
        image: nginx:latest
        restart: unless-stopped
        ports:
            - 80:80
        volumes:
            - ./nginx/conf:/etc/nginx/conf.d
            - ./test-vue-nginx-admin/dist/:/usr/share/nginx/html/admin
            - ./test-vue-nginx/dist:/usr/share/nginx/html/client

    front-end-1:
        container_name: front-end-1
        build:
          context: ./test-vue-nginx
          dockerfile: Dockerfile
        volumes:
          - ./test-vue-nginx/:/app
          - /app/node_modules

    front-end-2:
        container_name: front-end-2
        build:
          context: ./test-vue-nginx-admin
          dockerfile: Dockerfile
        ports:
          - "8083:80"
        volumes:
          - ./test-vue-nginx-admin/:/app
          - /app/node_modules
          
    back-end:
        build: ./Test-Spring-Nginx
        container_name: back-end
        restart: unless-stopped
        working_dir: /app
        volumes: 
          - ./Test-Spring-Nginx/:/app
        environment:
          - TZ=Asia/Ho_Chi_Minh
          
 