version: "3.7"

services:
    nginx:
        container_name: nginx
        depends_on:
          - front-end-1
          - front-end-2
        image: nginx:latest
        restart: unless-stopped
        ports:
            - 80:80
        volumes:
            - ./nginx/conf:/etc/nginx/conf.d

    front-end-1:
        container_name: front-end-1
        depends_on:
          - back-end
        build:
          context: ./test-vue-nginx
          dockerfile: Dockerfile
        ports:
            - 8083:80
        volumes:
          - ./test-vue-nginx/:/app
          - /app/node_modules

    front-end-2:
        container_name: front-end-2
        depends_on:
          - front-end-1
          - back-end
        build:
          context: ./test-vue-nginx-admin
          dockerfile: Dockerfile
        ports:
          - 8084:80
        volumes:
          - ./test-vue-nginx-admin/:/app
          - /app/node_modules
          
    back-end:
        build: ./Test-Spring-Nginx
        container_name: back-end
        restart: unless-stopped
        working_dir: /app
        volumes: 
          - ./Test-Spring-Nginx/:/app
        environment:
          - TZ=Asia/Ho_Chi_Minh
          
 