version: "1"

services:
  minio:
    image: minio/minio:latest
    hostname: minio
    ports:
      - "9000:9000"
      - "9099:9099"
    environment:
      MINIO_ROOT_USER: root
      MINIO_ROOT_PASSWORD: buiquanghieu
    volumes:
      - ./minIO/storage-minio:/data
    command: server --address ":9099" --console-address ":9000" /data
    restart: unless-stopped # necessary since it's failing to start sometimes

  server:
    build: ./Minio-Spring-Boot-Example
    ports:
      - '9999:9999'
    working_dir: /app
    volumes:
      - ./Minio-Spring-Boot-Example/:/app
    restart: unless-stopped